// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect__Bia.Data;

#nullable disable

namespace Proiect__Bia.Migrations
{
    [DbContext(typeof(Proiect__BiaContext))]
    partial class Proiect__BiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proiect__Bia.Models.Adoptator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Adoptator");
                });

            modelBuilder.Entity("Proiect__Bia.Models.Adoptie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AdoptatorID")
                        .HasColumnType("int");

                    b.Property<int?>("CopilID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAdoptiei")
                        .HasColumnType("datetime2");

                    b.Property<string>("StareAdoptie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AdoptatorID");

                    b.HasIndex("CopilID");

                    b.ToTable("Adoptie");
                });

            modelBuilder.Entity("Proiect__Bia.Models.Angajat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CentruID")
                        .HasColumnType("int");

                    b.Property<string>("Functie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CentruID");

                    b.ToTable("Angajat");
                });

            modelBuilder.Entity("Proiect__Bia.Models.Copil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataIntrariiInSistem")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNasterii")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocatieID")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvenientaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LocatieID");

                    b.HasIndex("ProvenientaID");

                    b.ToTable("Copil");
                });

            modelBuilder.Entity("Proiect__Bia.Models.Locatie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacitate")
                        .HasColumnType("int");

                    b.Property<string>("NumeCentru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Locatie");
                });

            modelBuilder.Entity("Proiect__Bia.Models.Provenienta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TipProvenienta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Provenienta");
                });

            modelBuilder.Entity("Proiect__Bia.Models.Adoptie", b =>
                {
                    b.HasOne("Proiect__Bia.Models.Adoptator", "Adoptator")
                        .WithMany("Adoptii")
                        .HasForeignKey("AdoptatorID");

                    b.HasOne("Proiect__Bia.Models.Copil", "Copil")
                        .WithMany()
                        .HasForeignKey("CopilID");

                    b.Navigation("Adoptator");

                    b.Navigation("Copil");
                });

            modelBuilder.Entity("Proiect__Bia.Models.Angajat", b =>
                {
                    b.HasOne("Proiect__Bia.Models.Locatie", "Centru")
                        .WithMany("Angajati")
                        .HasForeignKey("CentruID");

                    b.Navigation("Centru");
                });

            modelBuilder.Entity("Proiect__Bia.Models.Copil", b =>
                {
                    b.HasOne("Proiect__Bia.Models.Locatie", "Locatie")
                        .WithMany("Copii")
                        .HasForeignKey("LocatieID");

                    b.HasOne("Proiect__Bia.Models.Provenienta", "Provenienta")
                        .WithMany("Copii")
                        .HasForeignKey("ProvenientaID");

                    b.Navigation("Locatie");

                    b.Navigation("Provenienta");
                });

            modelBuilder.Entity("Proiect__Bia.Models.Adoptator", b =>
                {
                    b.Navigation("Adoptii");
                });

            modelBuilder.Entity("Proiect__Bia.Models.Locatie", b =>
                {
                    b.Navigation("Angajati");

                    b.Navigation("Copii");
                });

            modelBuilder.Entity("Proiect__Bia.Models.Provenienta", b =>
                {
                    b.Navigation("Copii");
                });
#pragma warning restore 612, 618
        }
    }
}
